"""Materialize a .env for the benchmark from Google Cloud Secret Manager.

The Vectorless deployment keeps its config in a single Secret Manager secret
(`server-config`, the engine's YAML), so the API keys live inside it rather than
as standalone secrets. This reads that secret with the caller's gcloud identity
(works locally and on a GCE VM via its service account) and extracts exactly what
the benchmark needs into a .env — never printing the values.

Mapping (server-config YAML -> env):
  auth.api_key              -> VECTORLESS_API_KEY  (engine bearer key)
  engine.llm.gemini.api_key -> GEMINI_API_KEY + GOOGLE_API_KEY  (baselines via google-genai)
  --base-url                -> VECTORLESS_BASE_URL  (the engine's Cloud Run URL)

Usage:
  python deploy/load_secrets.py \
      --project project-03250746-ec5b-4198-990 \
      --base-url https://vectorless-server-2rzh3kctga-uc.a.run.app \
      --out .env
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from typing import Any, Optional

import yaml


def _access_secret(project: str, secret: str) -> str:
    """Fetch the latest version of a secret via the gcloud CLI (uses ambient auth).

    `gcloud secrets versions access` returns the decoded payload on stdout."""
    res = subprocess.run(
        ["gcloud", "secrets", "versions", "access", "latest",
         f"--secret={secret}", f"--project={project}"],
        capture_output=True, text=True, shell=(sys.platform == "win32"),
    )
    if res.returncode != 0:
        raise SystemExit(f"failed to read secret {secret!r}: {res.stderr.strip()}")
    return res.stdout


def _dig(d: Any, *path: str) -> Optional[Any]:
    cur = d
    for key in path:
        if not isinstance(cur, dict) or key not in cur:
            return None
        cur = cur[key]
    return cur


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--secret", default="server-config")
    ap.add_argument("--base-url", required=True, help="engine Cloud Run URL")
    ap.add_argument("--out", default=".env")
    args = ap.parse_args()

    cfg = yaml.safe_load(_access_secret(args.project, args.secret)) or {}

    vl_key = _dig(cfg, "auth", "api_key")
    gem_key = _dig(cfg, "engine", "llm", "gemini", "api_key")
    # OpenAI key powers the vector_rag / full_context / judge baselines. The
    # engine itself may run on a different provider (e.g. GLM via the
    # Anthropic-compatible driver), so this is best-effort: pull it from the
    # engine LLM config or a top-level openai block if present.
    openai_key = _dig(cfg, "engine", "llm", "openai", "api_key") or _dig(cfg, "openai", "api_key")
    if not vl_key:
        raise SystemExit("server.auth.api_key not found in secret")
    if not gem_key:
        print("WARN: llm.gemini.api_key not found — Gemini baselines will fail", file=sys.stderr)
    if not openai_key:
        print("WARN: openai.api_key not found in secret — set OPENAI_API_KEY yourself "
              "for the vector_rag/full_context/judge baselines", file=sys.stderr)

    lines = [
        "# generated by deploy/load_secrets.py — do not commit",
        f"VECTORLESS_BASE_URL={args.base_url}",
        f"VECTORLESS_API_KEY={vl_key}",
    ]
    if gem_key:
        lines += [f"GEMINI_API_KEY={gem_key}", f"GOOGLE_API_KEY={gem_key}"]
    if openai_key:
        lines += [f"OPENAI_API_KEY={openai_key}"]

    with open(args.out, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")

    # report what was written WITHOUT exposing values
    wrote = ["VECTORLESS_BASE_URL", "VECTORLESS_API_KEY"] + (
        ["GEMINI_API_KEY", "GOOGLE_API_KEY"] if gem_key else []
    ) + (["OPENAI_API_KEY"] if openai_key else [])
    print(f"wrote {args.out} with: {', '.join(wrote)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
